### ISSUE TITLE
saveIncremental error on saving inclusion rules data in incremental mode

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortGenerator#59]
Reproducible example:

**previously exported cohort_inclusion.csv**

```
database_id,cohort_id,rule_sequence,name,description
optum,27,0,No COPD prior,
optum,28,0,No prior asthma,
```

Note - description field is empty.

The unexported function saveIncremental() will read that file and create a data frame

```
# A tibble: 10 x 4
   cohortDefinitionId ruleSequence name                                                                                   description
                <dbl>        <dbl> <chr>                                                                                  <lgl>      
 1                 27            0 No COPD prior                                                                          NA         
 2                 28            0 No prior asthma                                                                        NA 
```

Note description is NA

`data <- dplyr::bind_rows(previousData, data) `

with new data

```
   cohortDefinitionId ruleSequence                                                                                   name description
1                  27            0                                                                          No COPD prior            
2                  28            0                                                                        No prior asthma 
```

Note: empty string for description

Error message
```

Error in dplyr::bind_rows(previousData, data) : 
  Can't combine `..1$description` <logical> and `..2$description` <character>.
```

**Comment by gowthamrao** [comment]
hi @anthonysena  i have created a pull request for your consideration.

BTW in CohortDiagnostics this type of issue was being observed so many times, that i had to enforce conformance requirement in version 3 using a function called makeDataExportable here https://github.com/OHDSI/CohortDiagnostics/blob/main/R/Private.R#L123-L240

This will read the resultsDataModelSpecifications file and ensure that all files conform to the CohortDiagnsotics results data model. I do not think CohortGenerator needs this function, but if you think it is - may be its worth considering (maybe even for feature extraction and all OHDSI Packages as a best practice). This function not only checks for table conformance, but also data conformance (ie. key violations) - avoiding headaches while reviewing results output/inserting into results db.

We found several bugs in older versions of CohortDiagnostics after forcing this. Example - there was an edge case bug in Index_event_break_down sql that was causing key violations, which had never known before.
https://github.com/OHDSI/CohortDiagnostics/pull/894

**Comment by anthonysena** [comment]
Hi @gowthamrao - just trying to make sure I have a handle on the problem. I put together the following reprex to try and illustrate what you are describing:

``` r
df <- data.frame(database_id = "optum",
                 cohort_id = 27,
                 rule_sequence = 0,
                 name = "No COPD piror",
                 description = "")
df <- rbind(df, data.frame(database_id = "optum",
                           cohort_id = 28,
                           rule_sequence = 0,
                           name = "No piror asthma",
                           description = ""))
df
#>   database_id cohort_id rule_sequence            name description
#> 1       optum        27             0   No COPD piror            
#> 2       optum        28             0 No piror asthma

tf <- tempfile(fileext = ".csv")
CohortGenerator::saveIncremental(data = df,
                                 fileName = tf,
                                 database_id = df$database_id,
                                 cohort_id = df$cohort_id)

df2 <- CohortGenerator::readCsv(file = tf)
df2
#> # A tibble: 2 × 5
#>   databaseId cohortId ruleSequence name            description
#>   <chr>         <dbl>        <dbl> <chr>           <lgl>      
#> 1 optum            27            0 No COPD piror   NA         
#> 2 optum            28            0 No piror asthma NA
```

<sup>Created on 2022-09-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

You start with `df` which has an empty string for the `description` field. You then use `saveIncremental` to save it to a .csv file and then read it back into a new data.frame `df2` which then treats the `description` column as an NA value....which then causes issues elsewhere since the change in data type from a `character` to a `lgl` causes things to break. Do I have this right? 

I'd like to avoid having specific checks for named fields like `description` in the `saveIncremental` method as you proposed in #60. So I just want to make sure I've understood the problem and then I can see what options are available in `readr` when we write/read csv files like this one.

**Comment by anthonysena** [comment]
Adding some additional thoughts after some discussion with @schuemie. Having a mechanism to produce a "strong-typed" data.frame/tibble would be useful and something that we could enforce with the use of the `resultsDataModelSpecification.csv`. 

In CohortGenerator, the `readCsv` method is simply calling `readr::read_csv` under the hood. Looking at https://readr.tidyverse.org/reference/read_delim.html, we could allow for full specification of the `col_types` argument when reading a csv file to enforce the expected data types so that we're not having to use the default guessing mechanism of `readr`. In terms of our work here in OHDSI, if we have a `resultsDataModelSpecification.csv` that defines the expected output for a table, we can use this to construct a strongly typed data.frame for storing the data in memory and also when writing out the results. 

Relating this back to this specific issue, imagine we have an entry in the `resultsDataModelSpecification.csv` that defines the expected format of the inclusion rule (for bevity, I'll only include a subset of the columns):

| table_name       | column_name   | data_type |
|------------------|---------------|-----------|
| cohort_inclusion | database_id   | varchar   |
| cohort_inclusion | cohort_id     | bigint    |
| cohort_inclusion | rule_sequence | int       |
| cohort_inclusion | name          | varchar   |
| cohort_inclusion | description   | varchar   |


When we read the `cohort_inclusion` csv file, we'd pass to readr::read_csv the col_types translated from the `data_type` column in the `resultsDataModelSpecification.csv`. Here is an initial draft of that translation:

| readr col_type | resultsDataModelSpecification data type |
|----------------|-----------------------------------------|
| character      | varchar                                 |
| integer        | int                                     |
| number         | float                                   |
| double         | float                                   |
| logical        | int                                     |
| factor         | varchar                                 |
| date           | datetime                                |
| date time      | datetime                                |
| time           | datetime                                |

This would provide a more generic approach to how we enforce data type standards when moving from a data.frame/tibble to csv and back.

**Comment by gowthamrao** [comment]
Yes - we should be using resultsDataModelSpecification file when available.

The code for it is already here https://github.com/OHDSI/CohortDiagnostics/blob/befe0eb0e488fa8a4d308fed861cb03c64b67294/R/ResultsDataModel.R#L128-L200   thanks to @schuemie . This works for reading the files.

But, we also need ensure conformance while writing the file. See the makeDataExportable function i wrote for version 3 of Cohort Diagnostics here discussed above https://github.com/OHDSI/CohortGenerator/issues/59#issuecomment-1222295862  

These two functions will ensure conformance and type stability while either reading or writing.

**Comment by gowthamrao** [comment]
@anthonysena i am still experiencing this as an active issue when saving in incremental mode

> 
> Error in `dplyr::bind_rows()`:
> ! Can't combine `..1$description` <logical> and `..2$description` <character>.
> Run `rlang::last_error()` to see where the error occurred.

**Comment by ablack3** [comment]
I'm getting this error too.
```
Thread: Main
Message:  Can't combine `..1$description` <logical> and `..2$description` <character>.
Level:  FATAL
Time:  2023-05-05 18:08:12

Stack trace:
21: (function (condition) 
{
    if (is(condition, "error")) {
        log("FATAL"
20: signalCondition(cnd)
19: signal_abort(cnd)
18: cnd_signal(cnd)
17: (function (cnd) 
{
    cnd$call <- call
    cnd_signal(cnd)
})(list("Can't comb
16: signalCondition(cnd)
15: signal_abort(cnd, .file)
14: abort(message, class = c(class, "vctrs_error"), ..., call = vctrs_error_cal
13: stop_vctrs(message, class = c(class, "vctrs_error_incompatible"), x = x, y 
12: stop_incompatible(x, y, x_arg = x_arg, y_arg = y_arg, details = details, ..
11: stop_incompatible_type(x, y, x_arg = x_arg, y_arg = y_arg, `vctrs:::from_di
10: vec_default_ptype2(x = x, y = y, x_arg = x_arg, y_arg = y_arg, call = call,
9: (function () 
vec_default_ptype2(x = x, y = y, x_arg = x_arg, y_arg = y_arg,
8: vec_rbind(!!!dots, .names_to = .id)
7: withCallingHandlers(expr, error = function(cnd) {
    cnd$call <- call
    cn
6: fix_call(vec_rbind(!!!dots, .names_to = .id))
5: dplyr::bind_rows(previousData, data)
4: saveIncremental(data, fullFileName, cohort_definition_id = cohortDefinition
3: exportStats(table = tablesToExport$tableName[i], fileName = fileName, inclu
2: CohortGenerator::exportCohortStatsTables(connection = connection, cohortTab
1: execute(jobContext)
```

**Comment by gowthamrao** [comment]
Hi @anthonysena  i was wondering if you had an update on this issue. Running incremental mode is problematic with this issue/bug being still active

**Comment by ablack3** [comment]
Here's what I did. 

- Fork the CohortGenrator package, made these changes - https://github.com/OHDSI/CohortGenerator/pull/106/files
- Fork the CohortGenerator Module to use to my forked version of CohortGenerator package.

Easy! :)

**Comment by anthonysena** [comment]
This is now implemented in `develop` and more details on how to use the `colTypes` is described in https://github.com/OHDSI/CohortGenerator/pull/160#issue-2336926733 and https://readr.tidyverse.org/reference/read_delim.html#arguments (see `col_types` argument details)
