### ISSUE TITLE
readCohortSet and writeCohortSet functions

### ISSUE THREAD

**Issue by ablack3** [OHDSI/CohortGenerator#66]
As an enhancement I'm wondering if we could have `readCohortSet` and `writeCohortSet` functions that would save and load a cohortSet (i.e. a dataframe with  cohortId name cohortName, json, sql column) to and from disk.

I'm thinking the on disk format for a cohort set would be a folder with SQL and Json subfolders as well as a (potentially optional) cohortsToCreate.csv file that would specify the cohortId, name, cohortName columns.

**Comment by anthonysena** [comment]
Hey @ablack3 - I think `saveCohortDefinitionSet` and `getCohortDefinitionSet` should do the trick here:

https://ohdsi.github.io/CohortGenerator/reference/index.html#cohort-defintion-set

I'll close this out since I think these meet your needs but feel free to re-open if you see any gaps in terms of what you need.
